
language: ruby

rvm:
  - 2.4.0

addons:
  chrome: stable

install:
  - gem install cucumber
  - gem install watir

script:
  - cd EXAMPLE
  - HEADLESS_CHROME=true
  - LOG_LEVEL=DEBUG
  - cucumber -p example
  - ruby -e "puts 'OZ BUILD COMPLETED'"