language: ruby
sudo: required
rvm:
  - 2.4.0

addons:
  chrome: stable

install:
  - gem install cucumber
  - gem install watir

script:
  - cd EXAMPLE
  - export HEADLESS_CHROME=true
  - export LOG_LEVEL=DEBUG
  - cucumber -p example
  - ruby -e "puts 'OZ BUILD COMPLETED'"

after_success:
  - echo "Build comepleted Successfully"
  - ls
  - ./send_discord_webhook.sh success $WEBHOOK_URL

after_failure:
  - ./send_discord_webhook.sh failure $WEBHOOK_URL